In [48]:
# This file is basically based on the link below, although I have taken many part out from that for illustration purposes!
# https://deepnote.com/@ndungu/Implementing-KNN-Algorithm-on-the-Iris-Dataset-58Fkk1AMQki-VJOJ3mA_Fg

In [49]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

from sklearn import datasets
from sklearn.model_selection import train_test_split , KFold
from sklearn.preprocessing import Normalizer
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler

from collections import Counter

In [50]:
airports=pd.read_csv('data.csv')
print( len(airports) )
print( airports.head() )

7698
   airport_id                                       "name"        "city"  \
0           1                               Goroka Airport        Goroka   
1           2                               Madang Airport        Madang   
2           3                 Mount Hagen Kagamuga Airport   Mount Hagen   
3           4                               Nadzab Airport        Nadzab   
4           5  Port Moresby Jacksons International Airport  Port Moresby   

          "country"  "iata"  "icao"   "latitude"   "longitude"   "altitude"  \
0  Papua New Guinea     GKA    AYGA    -6.081690    145.391998         5282   
1  Papua New Guinea     MAG    AYMD    -5.207080    145.789001           20   
2  Papua New Guinea     HGU    AYMH    -5.826790    144.296005         5388   
3  Papua New Guinea     LAE    AYNZ    -6.569803    146.725977          239   
4  Papua New Guinea     POM    AYPY    -9.443380    147.220001          146   

    "timezone"  "dst"       "timezone_name"   "type"     "sourc

In [51]:
airports.columns

Index(['airport_id', ' "name"', ' "city"', ' "country"', ' "iata"', ' "icao"',
       ' "latitude"', ' "longitude"', ' "altitude"', ' "timezone"', ' "dst"',
       ' "timezone_name"', ' "type"', ' "source"'],
      dtype='object')

In [52]:
airports.describe()

airport_id   "latitude"   "longitude"    "altitude"   "timezone"
count   7698.000000  7698.000000   7698.000000   7698.000000  7345.000000
mean    5170.950117    25.808442     -1.390546   1015.873344     0.285303
std     3777.259930    28.404946     86.519162   1628.775132     5.716150
min        1.000000   -90.000000   -179.876999  -1266.000000   -12.000000
25%     1993.250000     6.907983    -78.974699     63.000000    -5.000000
50%     4068.000000    34.085701      6.375653    352.000000     1.000000
75%     7728.750000    47.239551     56.000599   1203.000000     4.000000
max    14110.000000    89.500000    179.951004  14472.000000    13.000000

In [53]:
# pd.DataFrame(airports[' \"longitude\"', ' \"latitude\"'], axis ='columns')
x = airports.drop(['airport_id', ' "name"', ' "city"', ' "country"', ' "iata"', ' "icao"',
   ' "timezone"', ' "dst"',
      ' "timezone_name"', ' "type"', ' "source"'], axis ='columns')
y = airports.drop(['airport_id', ' "name"', ' "city"', ' "iata"', ' "icao"',
       ' "latitude"', ' "longitude"', ' "altitude"', ' "timezone"', ' "dst"',
       ' "timezone_name"', ' "type"', ' "source"'], axis ='columns')

In [54]:
# Split the dataset
x = airports.iloc[:, -1]
y = airports.iloc[:, -1]
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.25, random_state=0) 
 
x_train= np.asarray(x_train)
y_train= np.asarray(y_train)

x_test= np.asarray(x_test)
y_test= np.asarray(y_test)

In [55]:
print(f'training set size: {x_train.shape[0]} samples \ntest set size: {x_test.shape[0]} samples')


training set size: 5773 samples 
test set size: 1925 samples


In [56]:
x.head()

0    OurAirports
1    OurAirports
2    OurAirports
3    OurAirports
4    OurAirports
Name:  "source", dtype: object

In [57]:
y.head()

0    OurAirports
1    OurAirports
2    OurAirports
3    OurAirports
4    OurAirports
Name:  "source", dtype: object

In [58]:
# Feature scaling
#sc_x = StandardScaler()
#x_train = sc_x.fit_transform(x_train)
#x_test = sc_x.transform(x_test)

In [59]:
# Normalizing dataset
scaler= Normalizer().fit(x_train) # the scaler is fitted to the training set
normalized_x_train= scaler.transform(x_train) # the scaler is applied to the training set
normalized_x_test= scaler.transform(x_test) # the scaler is applied to the test set

ValueError: could not convert string to float: 'OurAirports'

In [ ]:
print('x train before normalizing')
print(x_train[0:5])
print('\nx train after normalizing')
print(normalized_x_test[0:5])

x train before normalizing
       "latitude"   "longitude"   "altitude"
7492    46.029320      7.753366            0
2100    25.252800     55.364399           62
7086    31.275700    -85.713402          301
3101     5.069510     97.259201           28
2329   -39.000702    -67.620499          852

x train after normalizing
[[-0.19202085  0.85740073  0.47748506]
 [ 0.23402094  0.90889467  0.34517341]
 [ 0.03214984 -0.06367937  0.99745242]
 [ 0.28379846  0.95888395  0.        ]
 [-0.28783492  0.9264952   0.24239987]]


In [ ]:
len(x_train)

5773

In [ ]:
len(x_test)

1925

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5)

In [ ]:
knn.fit(x_train, y_train)

C:\Users\Dell\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neighbors\_classification.py:207: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [ ]:
# Predict the test set results
y_pred = knn.predict(x_test)
y_pred

array(['New Zealand', 'South Korea', 'United States', ..., 'Russia',
       'France', 'Greece'], dtype=object)

In [ ]:
knn.predict([[60.514099121094,22.262800216674,130]])

C:\Users\Dell\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


array(['Sweden'], dtype=object)

In [ ]:
# x_train

In [ ]:
# Evaluate the model
from sklearn.metrics import confusion_matrix
y_pred = knn.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
cm

array([[1, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 3, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [ ]:
print(accuracy_score(y_test, y_pred))
# or knn.score(x_test, y_test)

0.5262337662337663
