In [1]:
from sklearn import datasets
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.cluster import KMeans

In [2]:
crypto=pd.read_csv('dataset.csv')


In [9]:
crypto.shape

(72946, 10)

In [10]:
crypto.head()

Unnamed: 0        open        high         low       close  volume  \
0           0  112.900002  118.800003  107.142998  115.910004     0.0   
1           1    3.493130    3.692460    3.346060    3.590890     0.0   
2           2  115.980003  124.663002  106.639999  112.300003     0.0   
3           3    3.594220    3.781020    3.116020    3.371250     0.0   
4           4  112.250000  113.444000   97.699997  111.500000     0.0   

      marketCap                 timestamp crypto_name        date  
0  1.288693e+09  2013-05-05T23:59:59.999Z     Bitcoin  2013-05-05  
1  6.229819e+07  2013-05-05T23:59:59.999Z    Litecoin  2013-05-05  
2  1.249023e+09  2013-05-06T23:59:59.999Z     Bitcoin  2013-05-06  
3  5.859436e+07  2013-05-06T23:59:59.999Z    Litecoin  2013-05-06  
4  1.240594e+09  2013-05-07T23:59:59.999Z     Bitcoin  2013-05-07

In [22]:
litecoin = 'Litecoin'
crypto.drop(crypto.columns(litecoin, axis=1))

TypeError: 'Index' object is not callable

In [3]:
crypto.columns

Index(['Unnamed: 0', 'open', 'high', 'low', 'close', 'volume', 'marketCap',
       'timestamp', 'crypto_name', 'date'],
      dtype='object')

In [4]:
crypto.describe()

Unnamed: 0          open          high           low         close  \
count  72946.000000  72946.000000  7.294600e+04  72946.000000  7.294600e+04   
mean   36472.500000    870.194495  8.964124e+02    844.060640  8.712949e+02   
std    21057.840705   5231.654470  5.398613e+03   5079.389387  5.235508e+03   
min        0.000000      0.000000  1.022100e-10      0.000000  8.292000e-11   
25%    18236.250000      0.167916  1.767999e-01      0.158630  1.682982e-01   
50%    36472.500000      1.630666  1.717542e+00      1.541486  1.640219e+00   
75%    54708.750000     26.070557  2.756868e+01     24.791776  2.625195e+01   
max    72945.000000  67549.735581  1.621883e+05  66458.723733  6.756683e+04   

             volume     marketCap  
count  7.294600e+04  7.294600e+04  
mean   2.207607e+09  1.474922e+10  
std    9.617885e+09  7.501159e+10  
min    0.000000e+00  0.000000e+00  
25%    8.320618e+06  1.860432e+08  
50%    1.098756e+08  1.268539e+09  
75%    6.691398e+08  5.118618e+09  
max    3.509679e+11  1.274831e+12

In [5]:
# pd.DataFrame(airports[' \"longitude\"', ' \"latitude\"'], axis ='columns')
# import math
# x = crypto['open']
# for i in x:
#     math.floor(i)

# x.describe()
x = crypto['open']
y = crypto['close']

In [6]:
x.head()

0    112.900002
1      3.493130
2    115.980003
3      3.594220
4    112.250000
Name: open, dtype: float64

In [7]:
y.head()

0    115.910004
1      3.590890
2    112.300003
3      3.371250
4    111.500000
Name: close, dtype: float64

In [8]:
# Split the dataset
# x = airports.iloc[:, 0:13]
# y = airports.iloc[:, 13]
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.2, random_state=0)  

NameError: name 'train_test_split' is not defined

In [ ]:
# Feature scaling
sc_x = StandardScaler()
x_train = sc_x.fit_transform(x.values.reshape(-1,1))
x_test = sc_x.transform(x.values.reshape(-1,1))
print(x_train)
print(x_test)

[[-0.14475338]
 [-0.16566601]
 [-0.14416465]
 ...
 [-0.16538745]
 [-0.16633366]
 [-0.16624473]]
[[-0.14475338]
 [-0.16566601]
 [-0.14416465]
 ...
 [-0.16538745]
 [-0.16633366]
 [-0.16624473]]


In [ ]:
km = KMeans(n_clusters=3)
yp = km.fit_predict(x_train)
yp

array([0, 0, 0, ..., 0, 0, 0], dtype=int32)

In [ ]:
# Normalizing dataset
# scaler= Normalizer().fit(x_train) # the scaler is fitted to the training set
# scaler.head()

In [ ]:
# normalized_x_train= scaler.transform(x_train) # the scaler is applied to the training set
# normalized_x_test= scaler.transform(x_test) # the scaler is applied to the test set

In [ ]:
print('x train before normalizing')
print(x_train[0:5])
print('\nx train after normalizing')
print(normalized_x_test[0:5])

x train before normalizing
[[-0.14475338]
 [-0.16566601]
 [-0.14416465]
 [-0.16564668]
 [-0.14487763]]

x train after normalizing


NameError: name 'normalized_x_test' is not defined

In [ ]:
len(x_train)

58356

In [ ]:
len(x_test)

14590

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5)

In [ ]:
knn.fit(x_train, y_train)

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/neighbors/_classification.py:207: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [ ]:
# Predict the test set results
y_pred = knn.predict(x_test)
y_pred

array(['New Zealand', 'Japan', 'United States', ..., 'Russia', 'France',
       'Egypt'], dtype=object)

In [ ]:
knn.predict([[60.514099121094,22.262800216674,130]])

array(['China'], dtype=object)

In [ ]:
# x_train

In [ ]:
# Evaluate the model
from sklearn.metrics import confusion_matrix
y_pred = knn.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
cm

array([[3, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 8, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 2, 0],
       [0, 0, 0, ..., 0, 0, 1]])

In [ ]:
print(accuracy_score(y_test, y_pred))
# or knn.score(x_test, y_test)

0.7828571428571428
