In [179]:
# This file is basically based on the link below, although I have taken many part out from that for illustration purposes!
# https://deepnote.com/@ndungu/Implementing-KNN-Algorithm-on-the-Iris-Dataset-58Fkk1AMQki-VJOJ3mA_Fg

In [180]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

from sklearn import datasets
from sklearn.model_selection import train_test_split , KFold
from sklearn.preprocessing import Normalizer
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler

from collections import Counter

In [181]:
airports=pd.read_csv('data.csv')
print( len(airports) )
print( airports.head() )

7698
   airport_id                                       "name"        "city"  \
0           1                               Goroka Airport        Goroka   
1           2                               Madang Airport        Madang   
2           3                 Mount Hagen Kagamuga Airport   Mount Hagen   
3           4                               Nadzab Airport        Nadzab   
4           5  Port Moresby Jacksons International Airport  Port Moresby   

          "country"  "iata"  "icao"   "latitude"   "longitude"   "altitude"  \
0  Papua New Guinea     GKA    AYGA    -6.081690    145.391998         5282   
1  Papua New Guinea     MAG    AYMD    -5.207080    145.789001           20   
2  Papua New Guinea     HGU    AYMH    -5.826790    144.296005         5388   
3  Papua New Guinea     LAE    AYNZ    -6.569803    146.725977          239   
4  Papua New Guinea     POM    AYPY    -9.443380    147.220001          146   

    "timezone"  "dst"       "timezone_name"   "type"     "sourc

In [182]:
airports.columns

Index(['airport_id', ' "name"', ' "city"', ' "country"', ' "iata"', ' "icao"',
       ' "latitude"', ' "longitude"', ' "altitude"', ' "timezone"', ' "dst"',
       ' "timezone_name"', ' "type"', ' "source"'],
      dtype='object')

In [183]:
airports.describe()

airport_id   "latitude"   "longitude"    "altitude"   "timezone"
count   7698.000000  7698.000000   7698.000000   7698.000000  7345.000000
mean    5170.950117    25.808442     -1.390546   1015.873344     0.285303
std     3777.259930    28.404946     86.519162   1628.775132     5.716150
min        1.000000   -90.000000   -179.876999  -1266.000000   -12.000000
25%     1993.250000     6.907983    -78.974699     63.000000    -5.000000
50%     4068.000000    34.085701      6.375653    352.000000     1.000000
75%     7728.750000    47.239551     56.000599   1203.000000     4.000000
max    14110.000000    89.500000    179.951004  14472.000000    13.000000

In [184]:
# pd.DataFrame(airports[' \"longitude\"', ' \"latitude\"'], axis ='columns')

x = airports.drop(['airport_id', ' "name"', ' "city"', ' "country"', ' "iata"', ' "icao"',
    ' "timezone"', ' "dst"',
       ' "timezone_name"', ' "type"', ' "source"'], axis ='columns')
y = airports.drop(['airport_id', ' "name"', ' "city"', ' "iata"', ' "icao"',
       ' "latitude"', ' "longitude"', ' "altitude"', ' "timezone"', ' "dst"',
       ' "timezone_name"', ' "type"', ' "source"'], axis ='columns')

In [185]:
# Split the dataset
# x = airports.iloc[:, 0:13]
# y = airports.iloc[:, 13]
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.25, random_state=0)  

In [186]:
x.head()

"latitude"   "longitude"   "altitude"
0    -6.081690    145.391998         5282
1    -5.207080    145.789001           20
2    -5.826790    144.296005         5388
3    -6.569803    146.725977          239
4    -9.443380    147.220001          146

In [187]:
y.head()

"country"
0  Papua New Guinea
1  Papua New Guinea
2  Papua New Guinea
3  Papua New Guinea
4  Papua New Guinea

In [188]:
# Feature scaling
sc_x = StandardScaler()
x_train = sc_x.fit_transform(x_train)
x_test = sc_x.transform(x_test)

In [189]:
# Normalizing dataset
scaler= Normalizer().fit(x_train) # the scaler is fitted to the training set
normalized_x_train= scaler.transform(x_train) # the scaler is applied to the training set
normalized_x_test= scaler.transform(x_test) # the scaler is applied to the test set

In [190]:
print('x train before normalizing')
print(x_train[0:5])
print('\nx train after normalizing')
print(normalized_x_test[0:5])

x train before normalizing
[[ 0.70946782  0.09560437 -0.62243791]
 [-0.0245842   0.64722726 -0.58396215]
 [ 0.18820994 -0.98730448 -0.43564429]
 [-0.73767692  1.13262172 -0.60506176]
 [-2.2947148  -0.77767955 -0.09370646]]

x train after normalizing
[[-0.73767905  0.65051476 -0.18072124]
 [ 0.19010523  0.92055882 -0.34122055]
 [ 0.47882266 -0.86579203  0.14537202]
 [ 0.20796267  0.89138407 -0.4027232 ]
 [-0.86558588  0.34421708 -0.36369725]]


In [191]:
len(x_train)

5773

In [192]:
len(x_test)

1925

In [193]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5)

In [194]:
knn.fit(x_train, y_train)

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/neighbors/_classification.py:207: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [195]:
# Predict the test set results
y_pred = knn.predict(x_test)
y_pred

array(['New Zealand', 'Japan', 'United States', ..., 'Russia', 'France',
       'Egypt'], dtype=object)

In [196]:
knn.predict([[60.514099121094,22.262800216674,130]])

array(['China'], dtype=object)

In [197]:
# x_train

In [198]:
# Evaluate the model
from sklearn.metrics import confusion_matrix
y_pred = knn.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
cm

array([[3, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 8, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 2, 0],
       [0, 0, 0, ..., 0, 0, 1]])

In [199]:
print(accuracy_score(y_test, y_pred))
# or knn.score(x_test, y_test)

0.7828571428571428
